//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "mui/mui.h"
#include "mui/controls.h"
#include <mui/ds_window.h>

class DewesoftBridge;

class BaseSetupWindow : public Dewesoft::MUI::DSWindow
{
public:

protected:
    DewesoftBridge& bridge;

    Dewesoft::MUI::CaptionPanel versionTrackingPanel;
    Dewesoft::MUI::TextBox txtMajor;
    Dewesoft::MUI::TextBox txtMinor;
    Dewesoft::MUI::TextBox txtRevision;
    Dewesoft::MUI::TextBox txtBuild;
    Dewesoft::MUI::CaptionPanel revisionPanel;
    Dewesoft::MUI::Memo revisionHistoryMemo;

    BaseSetupWindow(Dewesoft::MUI::WindowPtr& ui, DewesoftBridge& bridge, std::string pathToXmlFile) : DSWindow (ui, pathToXmlFile), bridge(bridge)
    {
        // connect class to UI controls
        versionTrackingPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "versionTrackingPanel");
        txtMajor = Dewesoft::MUI::TextBox::Connect(ui, "txtMajor");
        txtMinor = Dewesoft::MUI::TextBox::Connect(ui, "txtMinor");
        txtRevision = Dewesoft::MUI::TextBox::Connect(ui, "txtRevision");
        txtBuild = Dewesoft::MUI::TextBox::Connect(ui, "txtBuild");
        revisionPanel = Dewesoft::MUI::CaptionPanel::Connect(ui, "revisionPanel");
        revisionHistoryMemo = Dewesoft::MUI::Memo::Connect(ui, "revisionHistoryMemo");
    }
};
