//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once
#include "mui/mui.h"
#include "mui/controls.h"
#include <mui/ds_window.h>

class DewesoftBridge;

class BaseSetupWindow : public Dewesoft::MUI::DSWindow
{
public:

protected:
    DewesoftBridge& bridge;

    Dewesoft::MUI::CaptionPanel myPanel1;
    Dewesoft::MUI::Label textBoxLabel;
    Dewesoft::MUI::TextBox labelEdit;
    Dewesoft::MUI::Label selectedItemLabel;
    Dewesoft::MUI::ComboBox comboBox1;
    Dewesoft::MUI::StackPanel enableDisableStackPanel;
    Dewesoft::MUI::Button showModal;
    Dewesoft::MUI::CheckBox showHideTextBox;
    Dewesoft::MUI::CaptionPanel myPanel2;
    Dewesoft::MUI::TabControl TabTest;
    Dewesoft::MUI::TextBlock SampleText;
    Dewesoft::MUI::RadioButton Radio1;
    Dewesoft::MUI::RadioButton Radio2;
    Dewesoft::MUI::TextBlock ImageText;
    Dewesoft::MUI::DSDrawGrid channelGrid;

    BaseSetupWindow(Dewesoft::MUI::WindowPtr& ui, DewesoftBridge& bridge, std::string pathToXmlFile) : DSWindow (ui, pathToXmlFile), bridge(bridge)
    {
        // connect class to UI controls
        myPanel1 = Dewesoft::MUI::CaptionPanel::Connect(ui, "myPanel1");
        textBoxLabel = Dewesoft::MUI::Label::Connect(ui, "textBoxLabel");
        labelEdit = Dewesoft::MUI::TextBox::Connect(ui, "labelEdit");
        selectedItemLabel = Dewesoft::MUI::Label::Connect(ui, "selectedItemLabel");
        comboBox1 = Dewesoft::MUI::ComboBox::Connect(ui, "comboBox1");
        enableDisableStackPanel = Dewesoft::MUI::StackPanel::Connect(ui, "enableDisableStackPanel");
        showModal = Dewesoft::MUI::Button::Connect(ui, "showModal");
        showHideTextBox = Dewesoft::MUI::CheckBox::Connect(ui, "showHideTextBox");
        myPanel2 = Dewesoft::MUI::CaptionPanel::Connect(ui, "myPanel2");
        TabTest = Dewesoft::MUI::TabControl::Connect(ui, "TabTest");
        SampleText = Dewesoft::MUI::TextBlock::Connect(ui, "SampleText");
        Radio1 = Dewesoft::MUI::RadioButton::Connect(ui, "Radio1");
        Radio2 = Dewesoft::MUI::RadioButton::Connect(ui, "Radio2");
        ImageText = Dewesoft::MUI::TextBlock::Connect(ui, "ImageText");
        channelGrid = Dewesoft::MUI::DSDrawGrid::Connect(ui, "channelGrid");
    }
};
